### ISSUE TITLE
Temporary issue: installing @emotion/core breaks things

### ISSUE THREAD

**Issue by AndrewPrifer** [AndrewPrifer/react-three-editable#14]
For now I decided to use Chakra UI to build the interface, and it might even stay that way because Chakra is awesome. However there's one tiny issue: if you add @emotion/core to your deps, things will break, and I can't even wrap my head around exactly how. See this issue: https://github.com/chakra-ui/chakra-ui/issues/2414.

There are two paths out of this: either I find a way for r3e's deps to stop leaking, or I replace the UI with a different solution. This will all happen before 1.0.0. If you happen to know how all of this works and how exactly things are breaking, and what bandaid I can apply, if any until Chakra fixes this, please let me know. 🙏

For now, however, I will keep using Chakra simply because it allows me to move extremely fast.

**Comment by AndrewPrifer** [comment]
### Update

It doesn't look like there is a good way to depend on emotion in a way that we can guarantee that it won't burden r3e's users.

To have a design system that is completely isolated from the outside, and maintainable at the same time, I think the best solution would be to use Reakit with tailwind. Tailwind provides a system UI-like theming API with design tokens, while being entirely static CSS, and Reakit provides low level primitives for functionality and accessibility.

**Comment by MioQuispe** [comment]
Sounds good. I couldn't use this precisely because of that issue.

**Comment by AndrewPrifer** [comment]
@MioQuispe this should be done in a day or two, I'm already working on it. Please keep an eye on the pre-releases.

**Comment by AndrewPrifer** [comment]
@MioQuispe this should be fixed in the 0.7.2 prerelease.
